#!/bin/sh

docker build \
			--build-arg VERSION=`cat .version` \
			--build-arg BUILD_DATE=`date +%F` \
			--build-arg BUILD_TIME=`date +%T%z` \
            --build-arg COMMIT=`git rev-parse --short HEAD` \
            -t $IMAGE_NAME .