name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Check out the repo
        uses: actions/checkout@v4


      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ vars.ORGANIZATION }}/${{ vars.REPOSITORY }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./build/package/Dockerfile
          push: true
          build-args: |
              "APPLICATION=${{ github.repository.owner }}/${{ github.repository.name }}"
              "BUILD_RFC3339=${{ env.RELEASE_DATE }}"
              "DESCRIPTION="${{ github.repository.DESCRIPTION }}"
              "PACKAGE=${{ github.repository.owner }}/${{ github.repository.name }}"
              "REVISION=${{ github.sha }}"
              "VERSION=${{ github.ref_name }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ vars.ORGANIZATION }}/${{ vars.REPOSITORY }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true